[server]
headless = true
enableCORS = true
enableXsrfProtection = false

[theme]
base="light"
primaryColor = "#4B7BFF"
backgroundColor = "#F5F6F7"
secondaryBackgroundColor = "#E3E3E3"
textColor = "#000000"

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false

[deprecation]
showfileUploaderEncoding = false

[client]
displayEnabled = true

[logger]
level = "info"

# [custom]
# hide_streamlit_watermark = true
